spring.application.name=quiz_1150119

#修改 server 啟動的 port，預設是 8080
#server.port=8083

# 設定資料庫連接
# 3306是連接 mysql 的 port；p1150119 是要連接的資料庫名稱
# rewriteBatchedStatements=true: 可以批次新增
spring.datasource.url=jdbc:mysql://localhost:33066/quiz_1150119?serverTimezone=Asia/Taipei&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
